apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: eba842dkr-go 
  janus-idp.io/tekton: eba842dkr-go
  backstage.io/kubernetes-id: eba842dkr-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eba842dkr-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  