apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: eba842dkr-go
  janus-idp.io/tekton: eba842dkr-go
  backstage.io/kubernetes-id: eba842dkr-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eba842dkr-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
