apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: eba842dkr-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: eba842dkr-go 
  name: eba842dkr-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: eba842dkr-go 
